---
name: pinch
version: 0.4.2.0
github: abhinav/pinch
license: BSD3
author: Abhinav Gupta
maintainer: mail@abhinavg.net
category: Development
synopsis: An alternative implementation of Thrift for Haskell.
description: |
  This library provides machinery for types to specify how they can be
  serialized and deserialized into/from Thrift payloads. It makes no
  assumptions on how these payloads are sent or received and performs no code
  generation. Types may specify how to be serialized and deserialized by
  defining instances of the @Pinchable@ typeclass by hand, with
  automatically derived instances by using generics or by using the pinch-gen code
  generator. Check the documentation in the "Pinch" module for more information.

  /What is Thrift?/ Apache Thrift provides an interface description language,
  a set of communication protocols, and a code generator and libraries for
  various programming languages to interact with the generated code. Pinch
  aims to provide an alternative implementation of Thrift for Haskell.

extra-source-files:
  - README.md
  - CHANGES.md
  - bench/pinch-bench/*.hs
  - bench/pinch-bench/*.cabal
  - examples/keyvalue/*.hs
  - examples/keyvalue/*.cabal
  - examples/keyvalue/*.thrift

ghc-options: -Wall

tested-with: GHC == 8.10.2, GHC == 8.8.3, GHC == 8.6.5, GHC == 8.4.4

dependencies:
  - base >= 4.7 && < 5
  - bytestring >= 0.10 && < 0.12
  - cereal >= 0.5.8.1 && < 0.6
  - containers >= 0.5 && < 0.7
  - network >= 3.1.2.0 && < 3.2
  - text >= 1.2 && < 1.3 || >= 2.0
  - unordered-containers >= 0.2 && < 0.3
  - vector >= 0.10 && < 0.14
  - semigroups >= 0.18 && < 0.21

build-tools:
  - hspec-discover >= 2.1

library:
  source-dirs: src
  exposed-modules:
    - Pinch
    - Pinch.Client
    - Pinch.Internal.Builder
    - Pinch.Internal.Exception
    - Pinch.Internal.FoldList
    - Pinch.Internal.Generic
    - Pinch.Internal.Message
    - Pinch.Internal.Pinchable
    - Pinch.Internal.RPC
    - Pinch.Internal.TType
    - Pinch.Internal.Value
    - Pinch.Protocol
    - Pinch.Protocol.Binary
    - Pinch.Protocol.Compact
    - Pinch.Server
    - Pinch.Transport
  dependencies:
    - array >= 0.5
    - deepseq >= 1.3 && < 1.5
    - ghc-prim
    - hashable >= 1.2 && < 1.5

tests:
  pinch-spec:
    main: Spec.hs
    source-dirs: tests
    dependencies:
      - async >= 2.2.2 && < 2.3
      - hspec >= 2.0
      - network-run >= 0.2.4 && < 0.3
      - pinch
      - QuickCheck >= 2.5
